"""
Cross-format validation test: PSFASCII vs Nutmeg ASCII (nutascii).
Requirement 1d.(iii): re-run the Stage 1 sizing once with -format nutascii,
parse with an independent reader, assert tight agreement, and print comparison.
"""

import os
import re
import math
import shutil
import tempfile
import unittest
import numpy as np

from circuits.two_stage_opamp_paper import generate_netlist
from cadence.spectre_runner import SpectreRunner
from cadence.psf_parser import parse_simulation_results


def parse_nutascii_ac(raw_file_path: str) -> dict:
    """
    Independent parser for Nutmeg ASCII (.raw) files generated by Spectre.
    """
    with open(raw_file_path, "r", errors="ignore") as f:
        content = f.read()

    # Find AC plot section
    ac_plot_idx = content.find("Plotname: AC Analysis")
    if ac_plot_idx == -1:
        raise ValueError("AC Analysis plot not found in nutascii raw file")

    ac_chunk = content[ac_plot_idx:]
    lines = ac_chunk.splitlines()

    # Find Variables section
    in_vars = False
    var_map = {}  # var_index -> var_name
    var_idx = 0
    val_start_line = 0

    for i, line in enumerate(lines):
        line = line.strip()
        if line.startswith("Variables:"):
            in_vars = True
            # First variable is on the same line after 'Variables:'
            tokens = line.split()
            if len(tokens) >= 3:
                var_map[int(tokens[1])] = tokens[2]
            continue
        if in_vars:
            if line.startswith("Values:"):
                val_start_line = i + 1
                break
            tokens = line.split()
            if len(tokens) >= 2:
                try:
                    idx = int(tokens[0])
                    name = tokens[1]
                    var_map[idx] = name
                except ValueError:
                    pass

    vout_idx = None
    freq_idx = None
    for idx, name in var_map.items():
        if name == "vout":
            vout_idx = idx
        elif name == "freq":
            freq_idx = idx

    if vout_idx is None:
        raise ValueError("Variable 'vout' not found in nutascii variables table")

    num_vars = len(var_map)
    data_lines = [l.strip() for l in lines[val_start_line:] if l.strip() and not l.startswith("END")]

    ac_data = []
    # In nutascii complex data:
    # point_idx <freq_re>,<freq_im>
    # <var1_re>,<var1_im>
    # ...
    cur_freq = None
    cur_vout = None
    var_pos = 0

    for line in data_lines:
        tokens = line.split()
        if len(tokens) == 2 and tokens[0].isdigit():
            # Start of a new frequency point
            var_pos = 0
            val_str = tokens[1]
        elif len(tokens) == 1:
            val_str = tokens[0]
        else:
            continue

        parts = val_str.split(",")
        if len(parts) == 2:
            re_val, im_val = float(parts[0]), float(parts[1])
            c_val = complex(re_val, im_val)
            if var_pos == 0:
                cur_freq = re_val
            elif var_pos == vout_idx:
                cur_vout = c_val
                if cur_freq is not None:
                    ac_data.append((cur_freq, cur_vout))
        var_pos += 1

    if not ac_data:
        raise ValueError("No AC data points parsed from nutascii raw file")

    freqs = np.array([x[0] for x in ac_data])
    vouts = np.array([x[1] for x in ac_data])
    mags_db = 20 * np.log10(np.maximum(np.abs(vouts), 1e-12))
    phases_deg = np.unwrap(np.angle(vouts)) * 180.0 / np.pi

    gain_db = float(np.max(mags_db))

    f3db = 0.0
    idx_3db = np.where(mags_db <= gain_db - 3.0)[0]
    if len(idx_3db) > 0:
        i = idx_3db[0]
        if i > 0:
            f1, f2 = freqs[i - 1], freqs[i]
            g1, g2 = mags_db[i - 1], mags_db[i]
            log_f = math.log10(f1) + (gain_db - 3.0 - g1) * (math.log10(f2) - math.log10(f1)) / (g2 - g1)
            f3db = float(10 ** log_f)
        else:
            f3db = float(freqs[0])

    ugbw = 0.0
    pm = 0.0
    cross_idx = np.where(np.diff(np.sign(mags_db)))[0]
    if len(cross_idx) > 0:
        i = cross_idx[0]
        f1, f2 = freqs[i], freqs[i + 1]
        g1, g2 = mags_db[i], mags_db[i + 1]
        log_f = math.log10(f1) + (0.0 - g1) * (math.log10(f2) - math.log10(f1)) / (g2 - g1)
        ugbw = float(10 ** log_f)
        p1, p2 = phases_deg[i], phases_deg[i + 1]
        phase_ugbw = p1 + (0.0 - g1) * (p2 - p1) / (g2 - g1)
        pm = float((180.0 + phase_ugbw + 180.0) % 360.0 - 180.0)
        if pm <= 0.0:
            pm += 360.0

    return {
        "gain_db": gain_db,
        "ugbw": ugbw,
        "pm": pm,
        "f3db": f3db,
    }


class TestNutasciiComparison(unittest.TestCase):
    def test_compare_psfascii_and_nutascii(self):
        """
        Runs Stage 1 midpoint sizing with both psfascii and nutascii,
        asserts agreement within tight tolerances, and prints comparison table.
        """
        mid_params = {
            "Wdiff": 3.4,
            "Wnb": 160.0,
            "Wpo": 5.5,
            "Wbp": 30.0,
            "Cc": 1.5,
        }
        netlist = generate_netlist(mid_params)
        runner = SpectreRunner()

        # 1. Run psfascii
        success_psf, raw_dir_psf, log_psf, err_psf = runner.run(netlist, fmt="psfascii")
        self.assertTrue(success_psf, f"PSFASCII run failed: {err_psf}")
        psf_results = parse_simulation_results(raw_dir_psf)

        # 2. Run nutascii
        success_nut, raw_file_nut, log_nut, err_nut = runner.run(netlist, fmt="nutascii")
        self.assertTrue(success_nut, f"NUTASCII run failed: {err_nut}")
        nut_results = parse_nutascii_ac(raw_file_nut)

        # Print comparison table
        print("\n" + "=" * 65)
        print("STAGE 1 CROSS-FORMAT VALIDATION (psfascii vs nutascii)")
        print("=" * 65)
        print(f"{'Metric':<15} | {'PSFASCII':<15} | {'NUTASCII':<15} | {'Difference':<15}")
        print("-" * 65)

        diff_gain = abs(psf_results["gain_db"] - nut_results["gain_db"])
        diff_ugbw = abs(psf_results["ugbw"] - nut_results["ugbw"]) / psf_results["ugbw"] * 100.0
        diff_pm = abs(psf_results["pm"] - nut_results["pm"])
        diff_f3db = abs(psf_results["f3db"] - nut_results["f3db"]) / psf_results["f3db"] * 100.0

        print(f"{'Gain (dB)':<15} | {psf_results['gain_db']:<15.3f} | {nut_results['gain_db']:<15.3f} | {diff_gain:<15.4f} dB")
        print(f"{'UGBW (MHz)':<15} | {psf_results['ugbw']/1e6:<15.4f} | {nut_results['ugbw']/1e6:<15.4f} | {diff_ugbw:<15.3f} %")
        print(f"{'PM (deg)':<15} | {psf_results['pm']:<15.2f} | {nut_results['pm']:<15.2f} | {diff_pm:<15.3f} deg")
        print(f"{'f3dB (kHz)':<15} | {psf_results['f3db']/1e3:<15.3f} | {nut_results['f3db']/1e3:<15.3f} | {diff_f3db:<15.3f} %")
        print("=" * 65 + "\n")

        # Clean up runner files
        runner.cleanup(raw_dir_psf)
        runner.cleanup(raw_file_nut)

        # Assert tight tolerances
        self.assertLess(diff_gain, 0.1, f"Gain discrepancy {diff_gain:.3f} dB exceeds 0.1 dB")
        self.assertLess(diff_ugbw, 2.0, f"UGBW discrepancy {diff_ugbw:.2f}% exceeds 2.0%")
        self.assertLess(diff_pm, 1.0, f"PM discrepancy {diff_pm:.2f} deg exceeds 1.0 deg")
        self.assertLess(diff_f3db, 2.0, f"f3dB discrepancy {diff_f3db:.2f}% exceeds 2.0%")


if __name__ == "__main__":
    unittest.main()
